name: xeus-sql
channels:
  - conda-forge
dependencies:
  - soci-sqlite
  - jupyterlab
  - xeus-sql
  - xeus-sqlite
  - numpy
  - pandas
  - rise
  - matplotlib
  # Builde dependencies
  - cmake
  # host dependencies
  - xeus=1.0.0
  - cppzmq
  - nlohmann_json
  - xtl=0.7.0
  - cpp-tabulate
  - soci-core
  - xproperty=0.11.0
  - xvega-bindings=0.0.10
  - xvega=0.0.10
